server:
  port: 7000
  tomcat:
    accesslog:
      enabled: true
  servlet:
    context-path: /api

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: false

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/db
    username: mindsit_dev
    password: mindsit_dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_jdbc_metadata_defaults: false
    open-in-view: false

custom:
  url:
    frontend: http://localhost:4500
    backend: http://localhost:"${server.port}"


spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: "${SPRING_MAIL_USERNAME}"
spring.mail.password: "${SPRING_MAIL_PASSWORD}"
spring.mail.enabled: false

spring.servlet.multipart.max-file-size: 100000000MB
spring.servlet.multipart.max-request-size: 100000000MB




