server:
  port: 7000
  tomcat:
    accesslog:
      enabled: true
  servlet:
    context-path: /api

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: false

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/db
    username: mindsit_dev
    password: mindsit_dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_jdbc_metadata_defaults: false

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: "${custom.email.username}"
spring.mail.password: "${custom.email.password}"

spring.servlet.multipart.max-file-size: 100000000MB
spring.servlet.multipart.max-request-size: 100000000MB
